"""Initial migration

Revision ID: 0051e98cc385
Revises: 
Create Date: 2026-10-03 23:51:13.767268
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import app.models.base

revision = '0051e98cc385'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_states',
    sa.Column('state_hash', sa.String(length=64), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('code_verifier', sa.String(length=128), nullable=True),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('expires_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_oauth_states')),
    sa.UniqueConstraint('state_hash', name=op.f('uq_oauth_states_state_hash'))
    )
    op.create_index(op.f('ix_oauth_states_expires_at'), 'oauth_states', ['expires_at'], unique=False)
    op.create_table('posts',
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('target_platforms', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_posts'))
    )
    op.create_index('ix_posts_status_created_at', 'posts', ['status', 'created_at'], unique=False)
    op.create_table('publishing_logs',
    sa.Column('publication_id', sa.Uuid(), nullable=True),
    sa.Column('post_id', sa.Uuid(), nullable=True),
    sa.Column('platform', sa.String(length=32), nullable=True),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_publishing_logs'))
    )
    op.create_index(op.f('ix_publishing_logs_created_at'), 'publishing_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_publishing_logs_post_id'), 'publishing_logs', ['post_id'], unique=False)
    op.create_index('ix_publishing_logs_publication_created', 'publishing_logs', ['publication_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_publishing_logs_publication_id'), 'publishing_logs', ['publication_id'], unique=False)
    op.create_table('social_accounts',
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('platform_account_id', sa.String(length=128), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('access_token_encrypted', sa.Text(), nullable=True),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=True),
    sa.Column('token_expires_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('scopes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('connected_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_social_accounts')),
    sa.UniqueConstraint('platform', 'platform_account_id', name='uq_social_accounts_platform_account')
    )
    op.create_index('ix_social_accounts_platform_status', 'social_accounts', ['platform', 'status'], unique=False)
    op.create_table('media',
    sa.Column('post_id', sa.Uuid(), nullable=True),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('file_type', sa.String(length=16), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_media_post_id_posts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_media_storage_key'))
    )
    op.create_index(op.f('ix_media_post_id'), 'media', ['post_id'], unique=False)
    op.create_table('publications',
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('social_account_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('external_post_id', sa.String(length=255), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('published_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_publications_post_id_posts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['social_account_id'], ['social_accounts.id'], name=op.f('fk_publications_social_account_id_social_accounts'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_publications')),
    sa.UniqueConstraint('post_id', 'social_account_id', name='uq_publications_post_account')
    )
    op.create_index(op.f('ix_publications_platform'), 'publications', ['platform'], unique=False)
    op.create_index(op.f('ix_publications_post_id'), 'publications', ['post_id'], unique=False)
    op.create_index(op.f('ix_publications_social_account_id'), 'publications', ['social_account_id'], unique=False)
    op.create_index('ix_publications_status_updated_at', 'publications', ['status', 'updated_at'], unique=False)
    op.create_table('scheduled_posts',
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('scheduled_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('platforms', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('dispatched_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_scheduled_posts_post_id_posts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scheduled_posts'))
    )
    op.create_index(op.f('ix_scheduled_posts_post_id'), 'scheduled_posts', ['post_id'], unique=False)
    op.create_index('ix_scheduled_posts_status_scheduled_at', 'scheduled_posts', ['status', 'scheduled_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_scheduled_posts_status_scheduled_at', table_name='scheduled_posts')
    op.drop_index(op.f('ix_scheduled_posts_post_id'), table_name='scheduled_posts')
    op.drop_table('scheduled_posts')
    op.drop_index('ix_publications_status_updated_at', table_name='publications')
    op.drop_index(op.f('ix_publications_social_account_id'), table_name='publications')
    op.drop_index(op.f('ix_publications_post_id'), table_name='publications')
    op.drop_index(op.f('ix_publications_platform'), table_name='publications')
    op.drop_table('publications')
    op.drop_index(op.f('ix_media_post_id'), table_name='media')
    op.drop_table('media')
    op.drop_index('ix_social_accounts_platform_status', table_name='social_accounts')
    op.drop_table('social_accounts')
    op.drop_index(op.f('ix_publishing_logs_publication_id'), table_name='publishing_logs')
    op.drop_index('ix_publishing_logs_publication_created', table_name='publishing_logs')
    op.drop_index(op.f('ix_publishing_logs_post_id'), table_name='publishing_logs')
    op.drop_index(op.f('ix_publishing_logs_created_at'), table_name='publishing_logs')
    op.drop_table('publishing_logs')
    op.drop_index('ix_posts_status_created_at', table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_oauth_states_expires_at'), table_name='oauth_states')
    op.drop_table('oauth_states')
    # ### end Alembic commands ###
